chore: add pytest to requirements and ensure newline at end of file

diff --git a/.github/workflows/4-step.yml b/.github/workflows/4-step.yml
--- a/.github/workflows/4-step.yml
+++ b/.github/workflows/4-step.yml
@@ -27,79 +27,79 @@ jobs:
       ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}
 
     steps:
-       - name: Checkout
-         uses: actions/checkout@v6
-         with:
-           fetch-depth: 0
+    - name: Checkout
+      uses: actions/checkout@v6
+      with:
+        fetch-depth: 0
 
-       - name: Get response templates
-         uses: actions/checkout@v6
-         with:
-           repository: skills/exercise-toolkit
-           path: exercise-toolkit
-           ref: v0.8.1
-           fetch-depth: 0
+    - name: Get response templates
+      uses: actions/checkout@v6
+      with:
+        repository: skills/exercise-toolkit
+        path: exercise-toolkit
+        ref: v0.8.1
+        fetch-depth: 0
 
-       - name: Find last comment
-         id: find-last-comment
-         uses: peter-evans/find-comment@v3
-         with:
-           repository: ${{ env.ISSUE_REPOSITORY }}
-           issue-number: ${{ env.ISSUE_NUMBER }}
-           direction: last
+    - name: Find last comment
+      id: find-last-comment
+      uses: peter-evans/find-comment@v3
+      with:
+        repository: ${{ env.ISSUE_REPOSITORY }}
+        issue-number: ${{ env.ISSUE_NUMBER }}
+        direction: last
 
-      - name: Update comment - checking work
-        uses: GrantBirki/comment@v2.1.1
-        with:
-          repository: ${{ env.ISSUE_REPOSITORY }}
-          issue-number: ${{ env.ISSUE_NUMBER }}
-          comment-id: ${{ steps.find-last-comment.outputs.comment-id }}
-          file: exercise-toolkit/markdown-templates/step-feedback/checking-work.md
-          edit-mode: replace
+    - name: Update comment - checking work
+      uses: GrantBirki/comment@v2.1.1
+      with:
+        repository: ${{ env.ISSUE_REPOSITORY }}
+        issue-number: ${{ env.ISSUE_NUMBER }}
+        comment-id: ${{ steps.find-last-comment.outputs.comment-id }}
+        file: exercise-toolkit/markdown-templates/step-feedback/checking-work.md
+        edit-mode: replace
 
-      # START: Check practical exercise
+    # START: Check practical exercise
 
-      - name: Check for pytest keyphrase in requirements.txt
-        id: check-for-pytest
-        continue-on-error: true
-        uses: skills/action-keyphrase-checker@v1
-        with:
-          text-file: requirements.txt
-          keyphrase: pytest
+    - name: Check for pytest keyphrase in requirements.txt
+      id: check-for-pytest
+      continue-on-error: true
+      uses: skills/action-keyphrase-checker@v1
+      with:
+        text-file: requirements.txt
+        keyphrase: pytest
 
-      - name: Check if tests directory exists
-        id: check-tests-dir
-        continue-on-error: true
-        run: |
-          if find . -name "tests" -type d | grep -q .; then
-            echo "Tests directory found"
-            exit 0
-          else
-            echo "Tests directory not found"
-            exit 1
-          fi
+    - name: Check if tests directory exists
+      id: check-tests-dir
+      continue-on-error: true
+      run: |
+        if find . -name "tests" -type d | grep -q .; then
+          echo "Tests directory found"
+          exit 0
+        else
+          echo "Tests directory not found"
+          exit 1
+        fi
 
-      - name: Update comment - step results
-        uses: GrantBirki/comment@v2.1.1
-        with:
-          repository: ${{ env.ISSUE_REPOSITORY }}
-          issue-number: ${{ env.ISSUE_NUMBER }}
-          comment-id: ${{ steps.find-last-comment.outputs.comment-id }}
-          edit-mode: replace
-          file: exercise-toolkit/markdown-templates/step-feedback/step-results-table.md
-          vars: |
-            step_number: 4
-            results_table:
-              - description: "Checked for pytest in requirements.txt"
-                passed: ${{ steps.check-for-pytest.outcome == 'success' }}
-              - description: "Checked if tests are added in a separate directory"
-                passed: ${{ steps.check-tests-dir.outcome == 'success' }}
+    - name: Update comment - step results
+      uses: GrantBirki/comment@v2.1.1
+      with:
+        repository: ${{ env.ISSUE_REPOSITORY }}
+        issue-number: ${{ env.ISSUE_NUMBER }}
+        comment-id: ${{ steps.find-last-comment.outputs.comment-id }}
+        edit-mode: replace
+        file: exercise-toolkit/markdown-templates/step-feedback/step-results-table.md
+        vars: |
+          step_number: 4
+          results_table:
+            - description: "Checked for pytest in requirements.txt"
+              passed: ${{ steps.check-for-pytest.outcome == 'success' }}
+            - description: "Checked if tests are added in a separate directory"
+              passed: ${{ steps.check-tests-dir.outcome == 'success' }}
 
-      # END: Check practical exercise
+    # END: Check practical exercise
 
-      - name: Fail job if not all checks passed
-        if: contains(steps.*.outcome, 'failure')
-        run: exit 1
+    - name: Fail job if not all checks passed
+      if: contains(steps.*.outcome, 'failure')
+      run: exit 1
 
   post_next_step_content:
     name: Post next step content
@@ -110,42 +110,42 @@ jobs:
       ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v6
+    - name: Checkout
+      uses: actions/checkout@v6
 
-      - name: Get response templates
-        uses: actions/checkout@v6
-        with:
-          repository: skills/exercise-toolkit
-          path: exercise-toolkit
-          ref: v0.8.1
+    - name: Get response templates
+      uses: actions/checkout@v6
+      with:
+        repository: skills/exercise-toolkit
+        path: exercise-toolkit
+        ref: v0.8.1
 
-      - name: Create comment - step finished
-        uses: GrantBirki/comment@v2.1.1
-        with:
-          repository: ${{ env.ISSUE_REPOSITORY }}
-          issue-number: ${{ env.ISSUE_NUMBER }}
-          file: exercise-toolkit/markdown-templates/step-feedback/step-finished-prepare-next-step.md
-          vars: |
-            next_step_number: 5
+    - name: Create comment - step finished
+      uses: GrantBirki/comment@v2.1.1
+      with:
+        repository: ${{ env.ISSUE_REPOSITORY }}
+        issue-number: ${{ env.ISSUE_NUMBER }}
+        file: exercise-toolkit/markdown-templates/step-feedback/step-finished-prepare-next-step.md
+        vars: |
+          next_step_number: 5
 
-      - name: Create comment - add step content
-        uses: GrantBirki/comment@v2.1.1
-        with:
-          repository: ${{ env.ISSUE_REPOSITORY }}
-          issue-number: ${{ env.ISSUE_NUMBER }}
-          file: ${{ env.STEP_5_FILE }}
+    - name: Create comment - add step content
+      uses: GrantBirki/comment@v2.1.1
+      with:
+        repository: ${{ env.ISSUE_REPOSITORY }}
+        issue-number: ${{ env.ISSUE_NUMBER }}
+        file: ${{ env.STEP_5_FILE }}
 
-      - name: Create comment - watching for progress
-        uses: GrantBirki/comment@v2.1.1
-        with:
-          repository: ${{ env.ISSUE_REPOSITORY }}
-          issue-number: ${{ env.ISSUE_NUMBER }}
-          file: exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md
+    - name: Create comment - watching for progress
+      uses: GrantBirki/comment@v2.1.1
+      with:
+        repository: ${{ env.ISSUE_REPOSITORY }}
+        issue-number: ${{ env.ISSUE_NUMBER }}
+        file: exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md
 
-      - name: Disable current workflow and enable next one
-        run: |
-          gh workflow disable "${{github.workflow}}"
-          gh workflow enable "Step 5"
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    - name: Disable current workflow and enable next one
+      run: |
+        gh workflow disable "${{github.workflow}}"
+        gh workflow enable "Step 5"
+      env:
+        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
